### ISSUE TITLE
So old code, I can not use it in TF 2.4,So sad! Can you help me ?

### ISSUE THREAD

**Issue by ross-Hr** [zhougroup/BAM#2]
when i use in GAT ,Oh  my GOD !!
Can you help me use BAM in GAT with keras  or TF 2.4 ?

**Comment by szhang42** [comment]
Hi, 

Thanks for your interest. We currently don't have the implementation in keras. For TF, We adapt our code from Graph Attention Networks (Veličković et al., ICLR 2018). Thanks.
